### ISSUE TITLE
Intermittent step failure trying to find nonexistent jquery file.

### ISSUE THREAD

**Issue by wholewheattoast** [npilon/planterbox-webdriver#11]
@npilon noticed odd webdriver/planterbox behavior today.

Every once in awhile running a test with local Firefox driver a css selector step will fail with the following

`Traceback (most recent call last):
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/planterbox/feature.py", line 198, in run_scenario
    step_fn(self, *step_arguments)
  File "/home/shawn/source/deus_lex/winslow/winslow/tests/features/__init__.py", line 251, in padded_wait_for_element_by_selector
    elems = wait_for_elem(test.browser, selector, int(seconds))
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/planterbox_webdriver/css_selector_steps.py", line 16, in wait_for_elem
    elems = find_elements_by_jquery(browser, sel)
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/planterbox_webdriver/css_selector_steps.py", line 43, in find_elements_by_jquery
    load_jquery(browser)
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/planterbox_webdriver/css_selector_steps.py", line 26, in load_jquery
    os.path.join(os.path.dirname(__file__), 'jquery-2.2.0.min.js')
IOError: [Errno 2] No such file or directory: '/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/planterbox_webdriver/jquery-2.2.0.min.js'`

Path exists but the file `jquery-2.2.0.min.js` does not.

Page in question already is loading jquery so there should be no need to shim it.

Test fails once or twice out of ten.

Let me know if you need more detail.

**Comment by npilon** [comment]
Should be addressed in https://github.com/npilon/planterbox-webdriver/releases/tag/0.3.4
