### ISSUE TITLE
Unicode in step throws exception

### ISSUE THREAD

**Issue by wholewheattoast** [npilon/planterbox-webdriver#6]
May be only/also an issue with planterbox.

Given step

```
Feature: Unicode
    While logged in
    A general search which includes unicode characters should't throw a loading error

    Scenario: A general search which includes unicode characters should't throw a loading error
        Given I point browser to "/"
        And I fill in $("#main-search input[name=q]") with "Iñtërnâtiônàlizætiøn"
        When I click $("#main-search .btn-default")
        Then there should not be an element matching $(".loading-error")
```

Get following exception

```
ERROR: Unicode (winslow.tests.features:unicode.feature)
While logged in
----------------------------------------------------------------------
Scenario: A general search which includes unicode characters should't throw a loading error
    Given I point browser to "/"
    And I fill in $("#main-search input[name=q]") with "Iñtërnâtiônàlizætiøn"
Traceback (most recent call last):
  File "/home/shawn/forks/planterbox/planterbox/__init__.py", line 201, in run_scenario
    step_fn(self, *step_arguments)
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/planterbox_webdriver/css_selector_steps.py", line 111, in fill_in_by_selector
    elem.send_keys(value)
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 328, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': typing})
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 454, in _execute
    return self._parent.execute(command, params)
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 199, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 392, in execute
    data = utils.dump_json(params)
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/selenium/webdriver/remote/utils.py", line 32, in dump_json
    return json.dumps(json_struct)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 0: unexpected end of data
```

**Comment by wholewheattoast** [comment]
@npilon not sure if this is the best solution to the problem?
https://github.com/wholewheattoast/planterbox-webdriver/blob/feature/unicode-happy/planterbox_webdriver/css_selector_steps.py#L111

**Comment by npilon** [comment]
I believe this is actually fixed by changes to `planterbox` - I should've been reading the feature files as `utf-8`.
