### ISSUE TITLE
Investigate make loading of jquery more robust.

### ISSUE THREAD

**Issue by wholewheattoast** [npilon/planterbox-webdriver#7]
Occasionally in running tests jquery doesn't load, leading to failed tests.  Is it possible to make loading jquery (when not already present) more robust?

```
ERROR: CSS-based formstuff (planterbox_webdriver.tests.test_css_selector_steps:css_forms.feature)
----------------------------------------------------------------------
Scenario: Everything fires up
    When I visit "basic_page"
    Then I fill in $("input[name='user']") with "A test string"
Traceback (most recent call last):
  File "/home/shawn/forks/planterbox/planterbox/__init__.py", line 201, in run_scenario
    step_fn(self, *step_arguments)
  File "/home/shawn/forks/planterbox-webdriver/planterbox_webdriver/css_selector_steps.py", line 109, in fill_in_by_selector
    elem = find_element_by_jquery(test, test.browser, selector)
  File "/home/shawn/forks/planterbox-webdriver/planterbox_webdriver/css_selector_steps.py", line 59, in find_element_by_jquery
    elements = find_elements_by_jquery(browser, selector)
  File "/home/shawn/forks/planterbox-webdriver/planterbox_webdriver/css_selector_steps.py", line 51, in find_elements_by_jquery
    """return ($ || jQuery)(arguments[0]).get();""", selector,
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute_script
    {'script': script, 'args':converted_args})['value']
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: $ is not defined
Stacktrace:
    at anonymous (file:///home/shawn/forks/planterbox-webdriver/planterbox_webdriver/tests/html_pages/basic_page.html line 69 > Function:1)
    at handleEvaluateEvent (file:///home/shawn/forks/planterbox-webdriver/planterbox_webdriver/tests/html_pages/basic_page.html:69)
```

**Comment by npilon** [comment]
Should be fixed.
